version: '3'

services:

    server:
        build:
          context: .
          dockerfile: ./docker/server/Dockerfile
        image: server
        command: --host="0.0.0.0"
        ports:
            - 8080:8080
